### ISSUE TITLE
(1.12.2) Cherry, Acer, and Ginkgo fences have missing textures.

### ISSUE THREAD

**Issue by 5h1b** [AYUTAKI-Shou/ChinjufuMod6.1.2#6]
### Mod list:
_Minecraft
Minecraft coder pack
Forge mod loader
Minecraft forge_

**Chinjufu Mod
JEI Mod
Cocricot Mod
CTM Mod
Immersive vehicles Mod
JEIDS Mod
Rojiura Mod
WorldEdit Mod**

Hey, 'I've noticed that' some fences have missing textures, and I'm wondering if you can fix these.
![2023-10-11_17 36 30](https://github.com/AYUTAKI-Shou/ChinjufuMod6.1.2/assets/62843852/378a3036-6dde-4c77-a306-2346cfa58872)
that's all.
love _Shiba_,

**Comment by 5h1b** [comment]
Mod version: 6.3.3
Forge 14.23.5.2859
Minecraft 1.12.2

**Comment by 5h1b** [comment]
### Mod list:
_Minecraft
Minecraft coder pack
Forge mod loader
Minecraft forge_

**Chinjufu Mod
JEI Mod
Cocricot Mod
CTM Mod
Immersive vehicles Mod
JEIDS Mod
Rojiura Mod
WorldEdit Mod**

**Comment by 5h1b** [comment]
Sorry,' about' The edits I made, and I was trying to make it look good.

**Comment by AYUTAKI-Shou** [comment]
Regarding your point, I don't think there's a problem I need to fix.
Please carefully check the name of the file you created.

![Image of fence in ChinjufuMod[1.12.2]6.3.3.](https://image02.seesaawiki.jp/c/i/chinjufumod_wiki/bFFIsyUa6Q.12.2_fence_231020.png)

**Comment by 5h1b** [comment]
This issue appears to have been fixed/was only on my end, I am closing this issue as it is 1 year old and is completed.
